name: MSBuild Project

on: 
  pull_request:
    branches-ignore: 
      - master
      - dev
  push:
    branches-ignore: 
      - master
      - dev

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Nuget Restore
      run: nuget NeverSkipLegDay\NeverSkipLegDay\NeverSkipLegDay\NeverSkipLegDay.csproj
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild NeverSkipLegDay\NeverSkipLegDay\NeverSkipLegDay\NeverSkipLegDay.csproj
